name: Prettier code formatter

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  check:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v6
      - name: Install Prettier 💾
        run: npm install --save-dev --save-exact prettier @shopify/prettier-plugin-liquid
      - name: Get changed files 📝
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            **/*.bib
            **/*.css
            **/*.html
            **/*.js
            **/*.json
            **/*.liquid
            **/*.md
            **/*.scss
            **/*.yml
            **/*.yaml
      - name: Prettier Check 🔎
        id: prettier
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: npx prettier --check $ALL_CHANGED_FILES
      - name: Create diff 📝
        # https://docs.github.com/en/actions/learn-github-actions/expressions#failure
        if: ${{ failure() }}
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          npx prettier --write $ALL_CHANGED_FILES
          git diff -- . ':(exclude)package-lock.json' ':(exclude)package.json' > diff.txt
          npm install -g diff2html-cli
          diff2html -i file -s side -F diff.html -- diff.txt
      - name: Upload html diff ⬆️
        id: artifact-upload
        if: ${{ failure() && steps.prettier.conclusion == 'failure' }}
        uses: actions/upload-artifact@v7
        with:
          name: HTML Diff
          path: diff.html
          retention-days: 7
      - name: Dispatch information to repository 🗣️
        if: ${{ failure() && steps.prettier.conclusion == 'failure' && github.event_name == 'pull_request' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: prettier-failed-on-pr
          client-payload: '{"pr_number": "${{ github.event.number }}", "artifact_url": "${{ steps.artifact-upload.outputs.artifact-url }}", "run_id": "${{ github.run_id }}"}'
